version: '3.8'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ''
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/config:/opt/airflow/config
    - ./airflow/plugins:/opt/airflow/plugins
    - ./script:/opt/airflow/script
    - ./sql:/opt/airflow/sql
    - ./.env:/opt/airflow/.env
    - ./dbt:/opt/airflow/dbt
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - data_network
  env_file: .env
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  # Metadata Database cho Airflow
  postgres:
    image: postgres:13
    mem_limit: 1024m
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - data_network

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  # Khởi tạo user và db chạy Airflow lần đầu
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    volumes:
      - ./airflow:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow

  # jupyter_lab:
  #   build:
  #     context: .
  #     dockerfile: ./jupyter/Dockerfile.jupyter
  #   container_name: jupyter_workspace
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jupyter/notebooks:/app/notebooks
  #     - ./jupyter/data:/app/data
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   restart: always
  #   networks:
  #     - data_network

  
  # mysql:
  #   image: mysql:8.0
  #   container_name: extract_db
  #   volumes:
  #     - extract_db:/var/lib/mysql
  #     - ./script/extract:/tmp/script/extract
  #     - ./sql/extract_db.sql:/docker-entrypoint-initdb.d/extract_db.sql
  #   ports:
  #     - "3307:3306"
  #   env_file: .env
  #   networks:
  #     - data_network


  minio: 
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data-volume:/data
    command: server /data --console-address ":9001"
    networks:
      - data_network

  # Data Warehouse (Staging + DWH)
  de_psql:
    image: postgres:14-alpine
    container_name: de_psql
    hostname: de_psql
    volumes:
      - postgres_data_h:/var/lib/postgresql/data
      - ./pg_hba.conf:/tmp/pg_hba.conf
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "hba_file=/tmp/pg_hba.conf"]
    expose:
      - "5433"
    ports:
      - "5433:5432" 
    env_file: .env
    networks:
      - data_network 

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.latest  # Dùng official image chuyên cho Postgres
    container_name: dbt_core
    depends_on:
      - de_psql  
    volumes:
      - ./dbt:/usr/app  # Mount thư mục code dbt của ta vào container
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml  # Mount thông tin đăng nhập database
    networks:
      - data_network
    working_dir: /usr/app
    entrypoint: ["dbt"]  # Đặt entrypoint sẵn để gọi lệnh sẽ ngắn gọn hơn

networks:
  data_network:
    driver: bridge

volumes:
  # extract_db:
  postgres-db-volume:
  postgres_data_h:
  minio-data-volume:
