FROM python:3.9-slim

WORKDIR /app

COPY jupyter/requirements_jupyter.txt .
RUN pip install --no-cache-dir -r requirements_jupyter.txt
RUN pip install --no-cache-dir jupyterlab

COPY ./jupyter .

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]